[ERROR] The provided path is not a valid directory: Ideathon 2025.pcap
[ERROR] The provided path is not a valid directory: Ideathon.pcap
[ERROR] The provided path is not a valid directory: /home/Dragon/Code/Github/MindWeaver/CyberSec/Notes/CyberSec/CTF's/Ideathon Blue/pcap_analyser-main/Ideathon.pcap
[INFO] Analyzing pcap files in directory: /home/Dragon/Code/Github/MindWeaver/CyberSec/Notes/CyberSec/CTF's/Ideathon Blue/pcap_analyser-main/
[INFO] Scan started at: 2025-04-14 14:49:55
Traceback (most recent call last):
  File "/home/Dragon/Code/Github/MindWeaver/CyberSec/Notes/CyberSec/CTF's/Ideathon Blue/pcap_analyser-main/black_list_parser.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[INFO] Analyzing file: /home/Dragon/Code/Github/MindWeaver/CyberSec/Notes/CyberSec/CTF's/Ideathon Blue/pcap_analyser-main/Ideathon.pcap
Traceback (most recent call last):
  File "/home/Dragon/Code/Github/MindWeaver/CyberSec/Notes/CyberSec/CTF's/Ideathon Blue/pcap_analyser-main/pcap_analyser.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
2025-04-14 14:49:55,972 INFO: Unique IP addresses have been saved in conversation_list.txt
[INFO] No malicious IP addresses found
[INFO] ----------- SCAN SUMMARY -----------
[INFO] Known blacklisted IPs: 176210
[INFO] Scanned files: 1
[INFO] Malicious IPs found: 0
[INFO] Unique IPs found: 0
[INFO] Pcap scanned size: 0 MB
[INFO] Time: 0 sec (0 m 0 s)
[INFO] Start Date: 2025-04-14 14:49:55
[INFO] End Date:   2025-04-14 14:49:55
[INFO] Pcap analysis completed!
[INFO] Pcap analysis log have been saved in /home/Dragon/Code/Github/MindWeaver/CyberSec/Notes/CyberSec/CTF's/Ideathon Blue/pcap_analyser-main//pcap_analyser.log
